version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login  --no-include-email --region us-west-2)
  build:
    commands:
      - echo Build started on 'date'
      - echo Building java
      - cd RiskAssessment
      - mvn compile
      - mvn package
      - echo Building the Docker image..
      - docker build -t service/riskapp .
      - docker tag service/riskapp 130475542568.dkr.ecr.us-west-2.amazonaws.com/pod-10-risk-assessment-registry:riskapp
      - echo "build ends.."
  post_build:
    commands:
    - echo Build completed on 'date'
    - echo Pushing the Docker image..
    - docker push 130475542568.dkr.ecr.us-west-2.amazonaws.com/pod-10-risk-assessment-registry:riskapp
    - echo Writing definitions file
    - printf '[{"name":"pod10riskapp-container","imageUri":"%s"}]' 130475542568.dkr.ecr.us-west-2.amazonaws.com/pod-10-risk-assessment-registry:riskapp > taskdefinition.json
artifacts:
  files:
    - RiskAssessment/taskdefinition.json